/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vcashorg_vcashwallet_wallet_PaymentProof */

#ifndef _Included_com_vcashorg_vcashwallet_wallet_PaymentProof
#define _Included_com_vcashorg_vcashwallet_wallet_PaymentProof
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vcashorg_vcashwallet_wallet_PaymentProof
 * Method:    get_payment_proof_address
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vcashorg_vcashwallet_wallet_PaymentProof_get_1payment_1proof_1address
        (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_PaymentProof
 * Method:    get_pubkey_from_proof_address
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vcashorg_vcashwallet_wallet_PaymentProof_get_1pubkey_1from_1proof_1address
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_PaymentProof
 * Method:    get_proof_address_from_pubkey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vcashorg_vcashwallet_wallet_PaymentProof_get_1proof_1address_1from_1pubkey
        (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_PaymentProof
 * Method:    create_payment_proof_signature
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vcashorg_vcashwallet_wallet_PaymentProof_create_1payment_1proof_1signature
        (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_PaymentProof
 * Method:    verify_payment_proof
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vcashorg_vcashwallet_wallet_PaymentProof_verify_1payment_1proof
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_PaymentProof
 * Method:    create_slatepack_message
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vcashorg_vcashwallet_wallet_PaymentProof_create_1slatepack_1message
        (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_PaymentProof
 * Method:    slate_from_slatepack_message
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vcashorg_vcashwallet_wallet_PaymentProof_slate_1from_1slatepack_1message
        (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_PaymentProof
 * Method:    sender_address_from_slatepack_message
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vcashorg_vcashwallet_wallet_PaymentProof_sender_1address_1from_1slatepack_1message
        (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_PaymentProof
 * Method:    create_random_uuid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vcashorg_vcashwallet_wallet_PaymentProof_create_1random_1uuid
        (JNIEnv *, jclass);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_PaymentProof
 * Method:    bytes_from_uuid
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vcashorg_vcashwallet_wallet_PaymentProof_bytes_1from_1uuid
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_PaymentProof
 * Method:    uuid_from_bytes
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vcashorg_vcashwallet_wallet_PaymentProof_uuid_1from_1bytes
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
