/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vcashorg_vcashwallet_wallet_NativeSecp256k1 */

#ifndef _Included_com_vcashorg_vcashwallet_wallet_NativeSecp256k1
#define _Included_com_vcashorg_vcashwallet_wallet_NativeSecp256k1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vcashorg_vcashwallet_wallet_NativeSecp256k1
 * Method:    secp256k1_ctx_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_vcashorg_vcashwallet_wallet_NativeSecp256k1_secp256k1_1ctx_1create
  (JNIEnv *, jobject);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_NativeSecp256k1
 * Method:    secp256k1_bind_switch
 * Signature: (JJ[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_vcashorg_vcashwallet_wallet_NativeSecp256k1_secp256k1_1bind_1switch
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_NativeSecp256k1
 * Method:    secp256k1_verify_ec_ecretKey
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vcashorg_vcashwallet_wallet_NativeSecp256k1_secp256k1_1verify_1ec_1ecretKey
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_vcashorg_vcashwallet_wallet_NativeSecp256k1
 * Method:    secp256k1_get_commitment
 * Signature: (JJ[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_vcashorg_vcashwallet_wallet_NativeSecp256k1_secp256k1_1get_1commitment
  (JNIEnv *, jobject, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
